baseURL = 'https://poudel-bibek.github.io'
languageCode = 'en-us'
title = ''
theme = 'PaperMod'

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowBreadCrumbs = false
  ShowPostNavLinks = false
  comments = false
  ShowShareButtons = false
  mainSections = ["posts", "pdfs"]
  
  # Favicon configuration
  [params.assets]
    disableFingerprinting = true
    favicon = "favicon.ico"
    favicon16x16 = "favicon-16x16.png"
    favicon32x32 = "favicon-32x32.png"
    apple_touch_icon = "apple-touch-icon.png"
    safari_pinned_tab = "safari-pinned-tab.svg"

  [params.homeInfoParams]
    Title = "👋 Hi, I am Bibek Poudel."
    Content1 = """Final year Computer Science Ph.D. student in the [Fluidic City Lab](https://fluidic-city.github.io) at [UTK](https://www.utk.edu/)."""
    Content2 = """My research, advised by [Dr. Weizi Li](https://weizi-li.github.io/) with support from [Center for Transportation Research](https://ctr.utk.edu/person/bibek-poudel/), lies at the intersection of reinforcement learning (RL), autonomous systems, and intelligent transportation - spanning from multi-agent simulation to real-world robots."""
    Content3 = """Currently, I am working on two projects: First, [developing](https://youtu.be/fmLydgvk2p4) RL agents that can simultaneously design and control urban environments to optimize outcomes for multiple stakeholders: pedestrians, vehicles, and urban planners. Second, I am also real-world transit routes"""
    Content4 = """Recently, I worked with [EPIC lab](https://epic.eecs.utk.edu) to develop a robotic wheelchair for personalized exertion control using Human-in-the-loop RL."""
    Content5 = """For details on my background and experiences, please check out my [resume](/pdfs/resume/). Besides my own research, I am developing [cowrite](https://cowrite.io/), a tool that helps researchers publish faster. Sometimes, I write on my [blog](/archives)."""

  [params.cover]
    hidden = true

[[params.socialIcons]]
name = "email"
url = "mailto:iambibek@me.com"

[[params.socialIcons]]
name = "linkedin"
url = "http://linkedin.com/in/poudelbibek"

[[params.socialIcons]]
name = "googlescholar"
url = "https://scholar.google.com/citations?user=PzBn1jgAAAAJ&hl=en"

[[params.socialIcons]]
name = "github"
url = "https://github.com/poudel-bibek"

[[params.socialIcons]]
name = "x"
url = "https://x.com/bibek_poudel_"

[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[menu.main]]
  name = 'Publications'
  pageRef = '/publications'
  weight = 20

[[menu.main]]
  name = 'Projects'
  pageRef = '/projects'
  weight = 30

[[menu.main]]
  name = 'Teaching'
  pageRef = '/teaching'
  weight = 40
  
[[menu.main]]
  name = 'Blog'
  pageRef = '/archives'
  weight = 50

[outputs]
home = ["HTML", "RSS", "JSON"]

[outputFormats.PDF]
mediaType = "application/pdf"
isPlainText = true
isHTML = false

[mediaTypes]
[mediaTypes."application/pdf"]
suffixes = ["pdf"]
