baseURL = 'https://poudel-bibek.github.io'
languageCode = 'en-us'
title = ''
theme = 'PaperMod'

[params.homeInfoParams]
Title = "Hi, I am Bibek Poudel."
Content1 = """A Computer Science Ph.D. student in the [Fluidic City lab](https://fluidic-city.github.io) at [UTK](https://www.utk.edu/). My current research, conducted alongside [Dr. Weizi Li](https://weizi-li.github.io/) and [Center for Transportation Research](https://ctr.utk.edu/person/bibek-poudel/), focuses on the application of Reinforcement Learning in autonomous systems like multi-agent simulation and real-world robots."""
Content2 = """For more details on my academic background and experiences, please check out [my CV](/pdfs/cv/). Besides research, I occasionally write on [my blog](/archives)."""

[params]
ShowReadingTime = true
ShowBreadCrumbs = false
ShowPostNavLinks = false
comments = false
ShowShareButtons= false

[params.cover]
hidden= true

[[params.socialIcons]]
name = "email"
url = "mailto:iambibek@me.com"

[[params.socialIcons]]
name = "linkedin"
url = "http://linkedin.com/in/poudelbibek"

[[params.socialIcons]]
name = "googlescholar"
url = "https://scholar.google.com/citations?user=PzBn1jgAAAAJ&hl=en"

[[params.socialIcons]]
name = "github"
url = "https://github.com/poudel-bibek"

[[params.socialIcons]]
name = "x"
url = "https://x.com/matrix_multiply"

[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[menu.main]]
  name = 'Publications'
  pageRef = '/publications'
  weight = 20

[[menu.main]]
  name = 'Projects'
  pageRef = '/projects'
  weight = 30

[[menu.main]]
  name = 'Lectures'
  pageRef = '/lectures'
  weight = 40
  
[[menu.main]]
  name = 'Blog'
  pageRef = '/archives'
  weight = 50

[outputs]
home = ["HTML", "RSS", "JSON"]

[outputFormats.PDF]
mediaType = "application/pdf"
isPlainText = true
isHTML = false

[mediaTypes]
[mediaTypes."application/pdf"]
suffixes = ["pdf"]