baseURL = 'https://poudel-bibek.github.io'
languageCode = 'en-us'
title = ''
theme = 'PaperMod'

[params]
  ShowReadingTime = true
  ShowBreadCrumbs = false
  ShowPostNavLinks = false
  comments = false
  ShowShareButtons = false
  mainSections = ["posts", "pdfs"]

  [params.homeInfoParams]
    Title = "👋 Hi, I am Bibek Poudel."
    Content1 = """A Computer Science Ph.D. student in the [Fluidic City Lab](https://fluidic-city.github.io) at the [UTK](https://www.utk.edu/)."""
    Content2 = """My research, advised by [Dr. Weizi Li](https://weizi-li.github.io/) with support from [Center for Transportation Research](https://ctr.utk.edu/person/bibek-poudel/), lies at the intersection of reinforcement learning (RL), autonomous systems, and intelligent transportation and spans from multi-agent simulations to real-world robots."""
    Content3 = """In my last project, I was part of a team that developed a robotic wheelchair designed to provide personalized mobility assistance to wheelchair users, balancing their physical exertion and mobility needs."""
    Content4 = """My current research focuses on leveraging RL to optimize urban environments for its diverse stakeholders. Specifically, I am interested in developing agents that can simultaneously make design decisions (such as configuring unsignalized pedestrian crosswalks) and control decisions (such as traffic signal timing for vehicles), addressing interrelated urban challenges that are often treated separately."""
    Content5 = """For more details on my academic background and experiences, please check out my [Resume](/pdfs/resume/). Besides research, I occasionally write on [my blog](/archives)."""

  [params.cover]
    hidden = true

[[params.socialIcons]]
name = "email"
url = "mailto:iambibek@me.com"

[[params.socialIcons]]
name = "linkedin"
url = "http://linkedin.com/in/poudelbibek"

[[params.socialIcons]]
name = "googlescholar"
url = "https://scholar.google.com/citations?user=PzBn1jgAAAAJ&hl=en"

[[params.socialIcons]]
name = "github"
url = "https://github.com/poudel-bibek"

[[params.socialIcons]]
name = "x"
url = "https://x.com/matrix_multiply"

[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[menu.main]]
  name = 'Publications'
  pageRef = '/publications'
  weight = 20

[[menu.main]]
  name = 'Projects'
  pageRef = '/projects'
  weight = 30

[[menu.main]]
  name = 'Lectures'
  pageRef = '/lectures'
  weight = 40
  
[[menu.main]]
  name = 'Blog'
  pageRef = '/archives'
  weight = 50

[outputs]
home = ["HTML", "RSS", "JSON"]

[outputFormats.PDF]
mediaType = "application/pdf"
isPlainText = true
isHTML = false

[mediaTypes]
[mediaTypes."application/pdf"]
suffixes = ["pdf"]
