baseURL = 'https://poudel-bibek.github.io'
languageCode = 'en-us'
title = ''
theme = 'PaperMod'

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowBreadCrumbs = false
  ShowPostNavLinks = false
  comments = false
  ShowShareButtons = false
  mainSections = ["posts", "pdfs"]
  customCSS = ["css/custom.css"]

  [params.homeInfoParams]
    Title = "👋 Hi, I am Bibek Poudel."
    Content1 = """Computer Science Ph.D. student in the [Fluidic City Lab](https://fluidic-city.github.io) at [UTK](https://www.utk.edu/)."""
    Content2 = """My research, advised by [Dr. Weizi Li](https://weizi-li.github.io/) with support from [Center for Transportation Research](https://ctr.utk.edu/person/bibek-poudel/), lies at the intersection of reinforcement learning (RL), autonomous systems, and intelligent transportation - spanning from multi-agent simulation to real-world robots."""
    Content3 = """In my recent project, I was part of [a team](https://epic.eecs.utk.edu) that developed a robotic wheelchair for personalized exertion control."""
    Content4 = """My [current research](https://youtu.be/fmLydgvk2p4) focuses on leveraging RL to optimize urban environments for its diverse stakeholders. Specifically, I am developing agents that can simultaneously design (e.g., placing pedestrian crosswalks) and control (e.g., traffic signal timing) decisions such environments."""
    Content5 = """For more details on my background and experiences, please check out my [resume](/pdfs/resume/). Besides research, I occasionally write on my [blog](/archives)."""

  [params.cover]
    hidden = true

[[params.socialIcons]]
name = "email"
url = "mailto:iambibek@me.com"

[[params.socialIcons]]
name = "linkedin"
url = "http://linkedin.com/in/poudelbibek"

[[params.socialIcons]]
name = "googlescholar"
url = "https://scholar.google.com/citations?user=PzBn1jgAAAAJ&hl=en"

[[params.socialIcons]]
name = "github"
url = "https://github.com/poudel-bibek"

[[params.socialIcons]]
name = "x"
url = "https://x.com/matrix_multiply"

[menu]
[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[menu.main]]
  name = 'Publications'
  pageRef = '/publications'
  weight = 20

[[menu.main]]
  name = 'Projects'
  pageRef = '/projects'
  weight = 30

[[menu.main]]
  name = 'Lectures'
  pageRef = '/lectures'
  weight = 40
  
[[menu.main]]
  name = 'Blog'
  pageRef = '/archives'
  weight = 50

[outputs]
home = ["HTML", "RSS", "JSON"]

[outputFormats.PDF]
mediaType = "application/pdf"
isPlainText = true
isHTML = false

[mediaTypes]
[mediaTypes."application/pdf"]
suffixes = ["pdf"]
